language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
  - "2.1.4"
  - "2.1.5"
  - "2.2.0"
  - "2.2.1"
gemfile:
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
services: sqlite3
before_script:
  - bundle exec rake db:migrate
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.2.1
      gemfile: gemfiles/rails_40.gemfile
